favicon: null
name: Bite Sized Victories
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7212766
  brandStrength: 0.05106383
  lightness: 0.8125
  brandColors:
    - '#ffffff'
    - '#fac261'
    - '#636363'
    - '#3b9d8e'
    - '#b2b2b2'
  rhythmicContrast: 0.9893617
typography_spectrum: 0.86058
layout_spectrum: 0.1680851
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
